service: guessword-api
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1

functions:
  guessword:
    handler: handler.guessword
    events:
      - http:
          path: guessword
          method: any
